Upgrade to hydra-0.16
CardanoSolutions/kupo pull request #166
Opened 2024-03-22 08:58 UTC by locallycompact

Co-Authored by Daniel Firth <daniel.firth@iohk.io>

2024-03-27 05:03 UTC, ch1bo requested changes
Besides the code changes requested, it seems like this is not working in the end-to-end test.

In fact, Hydra end-to-end tests seem to be broken for longer already? I tried testing the last released kupo `2.8` against latest released hydra `0.15.0` and this doesn't work either. CC @KtorZ

2024-03-27 12:28 UTC, KtorZ commented on src/Kupo/Data/Hydra.hs
> +        convertOutput :: Babbage.BabbageTxOut (BabbageEra StandardCrypto) -> Output
Indeed, as per: https://github.com/CardanoSolutions/kupo/blob/master/.editorconfig

2024-03-29 16:49 UTC, v0d1ch commented
@KtorZ @ch1bo you could take a look at this. I can confirm that all tests pass and I could index Hydra 0.16 txs with Kupo locally.

2024-04-02 07:56 UTC, merged

2024-04-02 08:30 UTC, ch1bo commented
Well.. as this got merged, we should release hydra `0.16.0` soon then :)

2024-04-02 08:58 UTC, KtorZ commented
Note: I haven't tested the Hydra integration myself. I will in the upcoming days for the next Kupo release.